server:
  port: 8080
  servlet:
    context-path: /my-project
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
smalldoc:
  source-paths: #额外的源码路径（项目的源码路径默认已经包含在内，不需要再添加）
    - 'D:\ebook\技术源码\my-study\silentself-demo\spring-boot-demo\small-doc-demo\src\main\java'
  packages:
    - com.atdyl.smalldocdemo
  project-name: 我的文档
  enabled: true #默认为true
  url-pattern: /smalldoc/* #默认为/smalldoc/*