server:
  port: 8080

spring:
  data:
    mongodb:
#      host: localhost
#      port: 27017
#      username: swen
#      password: swen123456
      database: app
#      authentication-database: admin
      uri: mongodb://swen:swen123456@localhost:27017/admin?authMechanism=SCRAM-SHA-1
#      uri: mongodb://127.0.0.1:27017/app
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration