server:
  port: 8080

spring:
  profiles:
    active: dev



---
spring:
  profiles: dev
  redis:
#    redisson:
#      config: classpath:/redisson.yml
    host: localhost
    port: 6379

redisson:
  singleServerConfig:
    address: 127.0.0.1:6379

---
spring:
  profiles: prod