server:
  port: 8080

spring:
  application:
    name: elasticsearch
  data:
    elasticsearch:
      # elasticsearch集群名称，默认的是elasticsearch
      cluster-name: docker-cluster
      #节点的地址 注意api模式下端口号是9300，千万不要写成9200
      cluster-nodes: 192.168.1.80:9300
      #是否开启本地存储
      repositories:
        client.transport.ignore_cluster_name: true
#        enabled: true
